### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by cvalencia1991** [maherramadan78/to-do-list#7]
Hello, good Job on your project there are also a couple of issues that you need to implement 
- try to implement more DRY and do Modules to distribute the project 
- Implement a live demo for this project 
- Change the licenses it slicenseseams that you copy the project 
<img width="814" alt="image" src="https://user-images.githubusercontent.com/107327344/230521481-15483f48-6c58-4ab4-905b-343437392880.png">
Have a great day and coding !!

**Comment by maherramadan78** [comment]
Good morning , this guy shoaib qureshi was my partner code we did this Project as group
I did not copy any Project .

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: Cesar ***@***.***>
Enviado: viernes, 7 de abril de 2023 12:20 a. m.
Para: ***@***.***>
CC: ***@***.***>
Asunto: [maherramadan78/to-do-list] Issues (Issue #7)


Hello, good Job on your project there are also a couple of issues that you need to implement

  *   try to implement more DRY and do Modules to distribute the project
  *   Implement a live demo for this project
  *   Change the licenses it slicenseseams that you copy the project

[image]<https://user-images.githubusercontent.com/107327344/230521481-15483f48-6c58-4ab4-905b-343437392880.png>
Have a great day and coding !!

**Comment by cvalencia1991** [comment]
this project doesn't have any collaborations, also it does not appear in your GitHub project, so please change your name
